version: '3.5'

services:
  client:
    container_name: tunebook-app
    build:
      context: ../../client
      dockerfile: Dockerfile
    volumes:
      - '../../client:/usr/tunebook-app'
      - '/usr/tunebook-app/node_modules'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      proxynet:


networks:
  proxynet:
    external: true