version: '3.5'

services:
  db:
    container_name: tunebook-db
    image: 'mongo'
    volumes:
      - tunebook_db_data_container:/data/db
    networks:
      - proxynet

  client:
    container_name: tunebook-app
    stdin_open: true
    tty: true
    build:
      context: ../../client
      dockerfile: Dockerfile
    volumes:
      - '../../client:/usr/tunebook-app'
      - '/usr/tunebook-app/node_modules'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3001:80
    networks:
      proxynet:
  api:
    container_name: tunebook-api
    depends_on:
      - db
    build:
      context: ../../api
      dockerfile: Dockerfile
    volumes:
      - '../../api:/usr/api'
      - '/usr/tunebook/node_modules'
    ports:
      - 3002:3000
    networks:
      proxynet:


  admin-db:
    container_name: tunebook-db-ui
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_SERVER=tunebook-db
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
      - db
    networks:
      - proxynet
    ports:
      - 3003:8081

networks:
  proxynet:
    external: true

volumes:
  tunebook_db_data_container:
    external: true